[package]
name = "iridium-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bytes = "1.5.0"
hex = "0.4.3"
logos = "0.14.0"
serialport = "4.3.0"
